Move index codebind logic to InterviewService
sde-sw/blazor-interview-app pull request #29
Opened 2021-09-12 11:12 UTC by thezerda

fixes #28 

Moved question creation/reset/filter/note/pin logic to InterviewService

2021-09-12 11:49 UTC, petrspelos commented
@thezerda good luck. with 80% coverage requirement, you've got some testing to do. 🤣 

In all seriousness, @PlesnikJakub, is that a requirement you added?

2021-09-12 12:47 UTC, PlesnikJakub commented
@petrspelos not really 😅 sonar cloud has this default quality gate. Anything with high duplicity rate, no coverage etc is rejected.. I guess I can update quality gate to be more suitable for this project.. it's matter of setting in sonar cloud.

2021-09-12 13:02 UTC, petrspelos requested changes
> I'm not done with the review, yet, btw. ☺️

2021-09-12 13:02 UTC, petrspelos commented on src/Client/Components/ExpansionList/AppExpansionList.razor.cs
> +    public IList<InterviewQuestion>? InterviewQuestions { get; set; }
Can we use a more generic `ICollection<T>` here? 🤔

2021-09-12 13:02 UTC, petrspelos commented on src/Client/Constants/InterviewConstants.cs
> +    public static readonly string NoteDialogTitle = "{0} notes";
You already separate the sections, I think commenting them is a bit too much. 👍

2021-09-12 13:02 UTC, petrspelos commented on src/Client/Extensions/RandomExtensions.cs
> +        return enumerable.OrderBy(_ => _random.Next()).Take(count);
Nice ☺️

2021-09-12 13:05 UTC, petrspelos commented
> @petrspelos not really 😅 sonar cloud has this default quality gate. Anything with high duplicity rate, no coverage etc is rejected.. I guess I can update quality gate to be more suitable for this project.. it's matter of setting in sonar cloud.

Yeah, we should probably change the quality gate for now, especially since setting up a coverage generation will require another tool. 

I'm currently figuring out a way of using coverlet to generate report for SonarCloud, so once we get around to creating a test project (which I might do if I'm bored enough), we'll have a tested way of adding code coverage. ☺️

2021-09-14 08:29 UTC, petrspelos requested changes
Just a couple of minor changes and I'd say this should be good to go. 😊 🎉 

Nice one, @thezerda.

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Components/ExpansionList/AppExpansionList.razor
>  }
```suggestion
}

```

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Components/ExpansionList/AppExpansionList.razor.cs
> +        return InterviewQuestions.Where(x => x.Contains(value));
It is slightly better practice to name your query variables according to the contents of the enumeration. It's just a bit easier to read.

```suggestion
        return InterviewQuestions.Where(q => q.Contains(value));
```

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Components/ExpansionList/ExpansionListItem/AppExpansionListItem.razor
> +}
```suggestion
}

```

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemContent/AppExpansionListItemContent.razor.cs
> +            throw new InvalidOperationException(nameof(Question));
The first parameter to `InvalidoperationException` is a message, I'd go for something like this:

```suggestion
            throw new InvalidOperationException($"{nameof(Question)} cannot be null.");
```

to communicate the `null` a little better.

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Components/ExpansionList/ExpansionListItem/ExpansionListItemTitle/AppExpansionListItemTitle.razor
> +}
```suggestion
}

```

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Components/Header/AppMainHeader.razor
> +                         <MudText Typo="Typo.caption" Align="Align.Justify">@e.Content.Substring(0, 100)...</MudText>
As the CI/CD says, you could be dereferencing a null reference here. 🤔 
Is that something Visual Studio tells you as well? 🤔

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Components/Header/AppMainHeader.razor.cs
> +        => OnSearchValue!.Invoke(value);
Rather then asserting not null, you should instead not call it if it's null.

```suggestion
    public void SearchText(string text)
        => OnSearchText?.Invoke(text);

    public void SearchValue(InterviewQuestion value)
        => OnSearchValue?.Invoke(value);
```

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Pages/Index.razor.cs
> +            throw new InvalidOperationException(nameof(_interviewService));
Again, I'd add a message instead of just the field name itself. 😉

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Pages/Index.razor.cs
> +            throw new InvalidOperationException(nameof(_interviewService));
Same as before

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Pages/Index.razor.cs
> +            _interviewService.InterviewQuestionLists[InterviewQuestionListType.CURRENT].Where(x => x.Equals(value));
```suggestion
            _interviewService.InterviewQuestionLists[InterviewQuestionListType.CURRENT].Where(q => q.Equals(value));
```

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Services/InterviewService.cs
> +                : InterviewQuestionLists[InterviewQuestionListType.CURRENT].Where(x => x.Contains(search)).AsEnumerable();
```suggestion
                : InterviewQuestionLists[InterviewQuestionListType.CURRENT].Where(q => q.Contains(search)).AsEnumerable();
```

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Services/InterviewService.cs
> +                : InterviewQuestionLists[InterviewQuestionListType.CURRENT].Where(x => x.Contains(search)).AsEnumerable();
And TBH this list solution....... it hits different

2021-09-14 08:29 UTC, petrspelos commented on src/Client/Shared/MainLayout.razor
> +</MudLayout>
```suggestion
</MudLayout>

```

2021-09-14 08:51 UTC, petrspelos approved these changes

2021-09-14 08:53 UTC, merged